config/routes.rb
BearBooks::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  post '/users/uploadBook' => 'users#uploadBook'
  post '/users/deleteBook' => 'users#deleteBook'
  post 'users/show' => 'users#show'
  get '/usersPool'  => 'users#usersPool'
  post 'users/likeBook' => 'users#likeBook'
  post 'users/addFriend' => 'users#addFriend'
  post 'users/deFriend' => 'users#deFriend'
  post 'acceptReq'=> 'users#acceptReq'
  post 'declineReq' => 'users#declineReq'
  post '/users/addComment' => 'users#addComment'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Manage Books', user_path(current_user)%></li>
  <li><%= link_to 'Social', '/usersPool'%></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bear Books" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bear Books" %>">
    <%= stylesheet_link_tag "application" %>
    <%# Foundation 5 won't work with Rails Turbolinks %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>



    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">

       <%= render 'layouts/messages' %>
      <div id="wrap">
        <div id="main">
       <%= yield %>
        </div>
      </div>
    </main>

    <div id="footer">
               <hr/>
      <div class="row">
        <div class="small-6 small-centered columns"> <h5> Thank you for visiting Bear Books. <br/> Developed By <em>Vigo</em> @ <a href="wustl.edu"> WUSTL </a> :) </h5> </div>
      </div>
    </div>

    <%# Foundation 5 won't work when application.js is included in HEAD %>
    <%= javascript_include_tag "application" %>
  </body>
</html>